### ISSUE TITLE
[Warning] directory does not exist

### ISSUE THREAD

**Issue by lucidaeon** [colstrom/git-ready#12]
Debian Jessie, installed cmake && libgit2

If I manually clone a repo, it skips over the repo, so it doesn't seem to be an auth/token issue.

> git-ready telusdigital
> [Info] Forking all telusdigital repositories to laurentr
> [######################################################################################################################################################] [135/135] [100.00%] [01:24] [00:00] [  1.59/s][Info] Cloning all forked repositories into /home/laurent/git
> [Failure] Failed to clone repository git@github.com:laurentr/repo.git to path /home/laurent/git/repo
> [Warning] /home/laurent/git/repo does not exist
> [#                                                                                                                                                     ] [  1/135] [  0.74%] [00:00] [00:01] [106.60/s][Failure] Failed to clone repository git@github.com:laurentr/repo2.git to path /home/laurent/git/repo2
> [Warning] /home/laurent/git/repo2 does not exist

**Comment by colstrom** [comment]
Does your `ssh-agent` have a key with access to that repository? That error is generated here:

https://github.com/colstrom/git-ready/blob/master/lib/git-ready/workspace.rb#L27-L28

**Comment by killerwails-zz** [comment]
I had the same issue. I checked my keys and generated the Access Token manually. Things worked smoothly after that. I'm running Ubuntu 15.10 and the ssh-agent has issue with elliptical keys sometimes.
